query generalPageCollectionQuery($preview: Boolean!, $slug: String!) {
  generalPageCollection(preview: $preview, where: { slug: $slug }) {
    items {
      title
      bodyModulesCollection {
        items {
          __typename
          # ... on Paragraph {
          #   paragraph
          # }
          # ... on Image {
          #   image {
          #     url
          #   }
          # }
        }
      }
    }
  }
}
